set dotenv-load := true

mister_ip := env_var_or_default("MISTER_IP", "192.168.1.79")

# List available recipes
default:
    @just --list

# Build frontend and ARM binary (mode: release or release-dev)
build mode="release-dev": build-frontend (build-1fpga mode)

# Build the JS frontend
build-frontend:
    npm run build

# (Re-)build the Docker builder image when the Dockerfile changes
docker-image:
    docker build -f ./docker/armv7/de10nano.Dockerfile . -t 1fpga:armv7

# Build the cross-compile image only if it isn't already present.
_ensure-docker-image:
    @docker image inspect 1fpga:armv7 > /dev/null 2>&1 || just docker-image

# Build the ARM binary via Docker
build-1fpga mode="release-dev": _ensure-docker-image
    docker run -it -e "TERM=xterm-256color" -v "{{justfile_directory()}}":/app 1fpga:armv7 --bin one_fpga_bin --profile {{mode}}
    cp target/armv7-unknown-linux-gnueabihf/{{mode}}/one_fpga_bin target/armv7-unknown-linux-gnueabihf/{{mode}}/one_fpga

# Build and sign the binary
build-and-sign mode="release" public_key="": (build mode)
    #!/usr/bin/env bash
    set -euo pipefail
    key="{{public_key}}"
    if [ -z "$key" ]; then
        read -p "Enter path to public key: " key
    fi
    openssl pkeyutl -sign \
        -inkey "$key" \
        -out target/armv7-unknown-linux-gnueabihf/{{mode}}/one_fpga.sig \
        -rawin -in target/armv7-unknown-linux-gnueabihf/{{mode}}/one_fpga

# Deploy the frontend to the device
deploy-frontend: build-frontend
    rsync -raH --delete js/frontend/dist/ root@{{mister_ip}}:/root/frontend

# Create a new DB migration
new-migration name:
    #!/usr/bin/env bash
    set -euo pipefail
    ts=$(date +%Y-%m-%d-%H%M%S)
    dir="js/frontend/migrations/1fpga/${ts}_{{name}}"
    mkdir "$dir"
    echo "-- Add your migration here. Comments will be removed." > "$dir/up.sql"

# Update Patreon credits
patreon:
    LAST_RELEASE=$(git tag | sort -r | head -n1) npm run patreon

# Pull pre-built Quartus 17.0.2 image (theypsilon/quartus-lite-c5)
menu-core-image:
    docker build --platform linux/amd64 -t one-fpga-quartus:17.0.2 docker/quartus

# Build the Quartus image only if it isn't already present.
_ensure-menu-core-image:
    @docker image inspect one-fpga-quartus:17.0.2 > /dev/null 2>&1 || just menu-core-image

# Regenerate cores/menu-core-fpga/build_id.svh. BUILD_ID is the
# first 32 bits of a SHA-256 over the menu-core source tree (all
# .sv / .sdc / .qsf / .qpf files, excluding build_id.svh itself
# to avoid the self-referential cycle). Surfaces through the
# BUILD_ID register (0x80) so the host probe can confirm the RBF
# running on the device matches the source it was synthesized
# from.
#
# Content-hash rather than timestamp because Quartus's incremental
# build relies on file mtime — a fresh epoch every invocation would
# defeat caching even when nothing else changed. Write the new
# content to a temp file and `cmp` against the existing one; only
# overwrite when the hash actually differs, so unchanged builds
# keep the .svh's mtime and Quartus reuses prior synthesis output.
#
# Gitignored. Run automatically before every `just build-menu-core`;
# also safe to run by hand if you want to refresh the value out of
# band.
_gen-build-id:
    #!/usr/bin/env bash
    set -euo pipefail
    out=cores/menu-core-fpga/build_id.svh
    # Source set: everything Quartus actually consumes, minus
    # build_id.svh itself (would make the hash a fixed point of
    # its own output). `sort -z` for stable cross-platform order.
    hash=$( \
        find cores/menu-core-fpga \
            \( -name '*.sv' -o -name '*.sdc' -o -name '*.qsf' -o -name '*.qpf' -o -name '*.tcl' \) \
            ! -name 'build_id.svh' \
            -print0 \
        | sort -z \
        | xargs -0 sha256sum \
        | sha256sum \
        | cut -c1-8 \
    )
    tmp=$(mktemp)
    trap 'rm -f "$tmp"' EXIT
    {
        echo "// AUTO-GENERATED by just _gen-build-id — do not edit by hand."
        echo "// 32-bit content hash of menu-core-fpga sources (excluding this file)."
        echo "// Stable across rebuilds when no source changes — preserves the .svh"
        echo "// mtime so Quartus's incremental-compile cache stays hot."
        echo "\`define BUILD_ID 32'h${hash}"
    } > "$tmp"
    if [ ! -f "$out" ] || ! cmp -s "$tmp" "$out"; then
        mv "$tmp" "$out"
        echo "build_id.svh: BUILD_ID = 32'h${hash} (source changed; mtime touched)"
    else
        echo "build_id.svh: BUILD_ID = 32'h${hash} (unchanged; mtime preserved)"
    fi

# Compile the menu-core FPGA bitstream (requires cores/menu-core-fpga submodule)
build-menu-core: _ensure-menu-core-image _gen-build-id
    @test -f cores/menu-core-fpga/menu_core.qpf || \
        (echo "ERROR: cores/menu-core-fpga submodule not initialized. Run:" && \
         echo "  git submodule update --init --recursive" && \
         exit 1)
    docker run --rm -t \
        --platform linux/amd64 \
        -u "$(id -u):$(id -g)" \
        -v "{{justfile_directory()}}/cores/menu-core-fpga":/work \
        one-fpga-quartus:17.0.2 \
        --flow compile menu_core.qpf

# Dump the 5 worst setup paths per clock to output_files/worst_*.txt
# using the existing fitter output (no rebuild). Use after a
# `just build-menu-core` to diagnose timing failures — the
# standard menu_core.sta.rpt only includes summary tables, but
# this recipe runs `report_timing` with -detail full_path so each
# combinational chain is enumerated cell-by-cell.
report-timing: _ensure-menu-core-image
    docker run --rm -t \
        --platform linux/amd64 \
        -u "$(id -u):$(id -g)" \
        -v "{{justfile_directory()}}/cores/menu-core-fpga":/work \
        --entrypoint quartus_sta \
        one-fpga-quartus:17.0.2 \
        -t report_worst_paths.tcl

# Open an interactive shell in the Quartus container
quartus-shell:
    docker run --rm -it \
        --platform linux/amd64 \
        -u "$(id -u):$(id -g)" \
        -v "{{justfile_directory()}}/cores/menu-core-fpga":/work \
        --entrypoint /bin/bash \
        one-fpga-quartus:17.0.2

# Deploy the built menu-core .rbf to the device, then reboot so
# the FPGA reloads the new bitstream. MiSTer loads menu.rbf at
# boot, so a fresh deploy is invisible until the device restarts —
# skipping this step was the cause of multiple wasted debug cycles
# during Phase 4 (BUILD_ID register exists partly because of this).
#
# The reboot ssh call will exit non-zero (the connection drops);
# the `-` prefix on the line tells just to ignore that. We then
# poll `ping -c1` until the device is reachable again, so the
# next recipe in a chain (e.g. `demo-menu-ui-v2`) doesn't fire
# scp before sshd is back up.
deploy-menu-core: build-menu-core
    scp cores/menu-core-fpga/output_files/menu_core.rbf root@{{mister_ip}}:/media/fat/menu.rbf
    -ssh root@{{mister_ip}} 'sync; reboot'
    @echo "deploy-menu-core: waiting for device to come back online…"
    @sleep 5
    @until ping -c1 -W1 {{mister_ip}} >/dev/null 2>&1; do sleep 1; done
    @until ssh -o ConnectTimeout=2 -o StrictHostKeyChecking=no root@{{mister_ip}} true 2>/dev/null; do sleep 1; done
    @echo "deploy-menu-core: device back up"

# Cross-compile the menu-core host probe binary for armv7 (musl, static)
# Uses a separate community image because the device's glibc is older
# than what the main firmware's bookworm-based image links against.
build-menu-core-host mode="release-dev":
    docker run --rm -t \
        -e RUSTUP_AUTO_INSTALL=0 \
        -v "{{justfile_directory()}}":/home/rust/src \
        messense/rust-musl-cross:armv7-musleabihf \
        cargo build --target armv7-unknown-linux-musleabihf --bin one_fpga_menu_core --profile {{mode}} --no-default-features --features=platform_de10

# Deploy the host probe binary to the device
deploy-menu-core-host mode="release-dev": (build-menu-core-host mode) _kill-fpga-users
    scp target/armv7-unknown-linux-musleabihf/{{mode}}/one_fpga_menu_core root@{{mister_ip}}:/media/fat/one_fpga_menu_core

# Cross-compile the menu-core demo binary (bouncing-rect animation)
build-menu-demo mode="release-dev":
    docker run --rm -t \
        -v "{{justfile_directory()}}":/home/rust/src \
        messense/rust-musl-cross:armv7-musleabihf \
        cargo build --target armv7-unknown-linux-musleabihf --bin menu_demo --profile {{mode}} --no-default-features --features=platform_de10

# Deploy the menu-core demo binary to the device
deploy-menu-demo mode="release-dev": (build-menu-demo mode) _kill-fpga-users
    scp target/armv7-unknown-linux-musleabihf/{{mode}}/menu_demo root@{{mister_ip}}:/media/fat/menu_demo

# Run the menu-core demo on the device (animation loop; Ctrl+C to stop)
demo-menu-core: _kill-fpga-users
    ssh -t root@{{mister_ip}} '/media/fat/menu_demo'

# Cross-compile the menu-ui launcher (React-on-Boa UI framework)
build-menu-ui mode="release-dev":
    docker run --rm -t \
        -e RUSTUP_AUTO_INSTALL=0 \
        -v "{{justfile_directory()}}":/home/rust/src \
        messense/rust-musl-cross:armv7-musleabihf \
        cargo build --target armv7-unknown-linux-musleabihf --bin menu_ui --profile {{mode}} --no-default-features --features=platform_de10

# Kill anything that might be holding the FPGA registers (MiSTer
# auto-starts after a reboot, the previous menu_ui run may still be
# attached, etc.). Best-effort.
_kill-fpga-users:
    -ssh root@{{mister_ip}} 'killall MiSTer 2>/dev/null; killall menu_ui 2>/dev/null; killall one_fpga_menu_core 2>/dev/null; killall menu_demo 2>/dev/null; true'

# Deploy the menu-ui binary to the device
deploy-menu-ui mode="release-dev": (build-menu-ui mode) _kill-fpga-users
    scp target/armv7-unknown-linux-musleabihf/{{mode}}/menu_ui root@{{mister_ip}}:/media/fat/menu_ui

# Deploy the menu-ui JS bundle to the device (used with --bundle for dev iteration)
deploy-menu-ui-bundle:
    # Root-level build runs `@1fpga/schemas` then `@1fpga/frontend` in the
    # right order; the latter imports the former, so building only frontend
    # would fail with "Cannot find module '@1fpga/schemas'".
    npm run build
    scp js/frontend/dist/menu_ui.js root@{{mister_ip}}:/media/fat/menu_ui_app.js

# Deploy a small test PNG to the device for menu-ui's <img> demo
deploy-menu-ui-test-png:
    scp docs/assets/osd/line_array.png root@{{mister_ip}}:/media/fat/menu_ui_test.png

# (Re-)generate the menu-ui N9 demo asset PNGs (host-side tool).
# Writes into docs/assets/menu-ui-demo/. The PNGs are committed,
# so only re-run when the demo's visual style changes.
gen-menu-ui-assets:
    cargo run --bin gen_demo_assets

# Deploy the menu-ui N9 demo assets (background + per-system icons)
# into /media/fat/menu_ui_assets/ on the device. Idempotent.
deploy-menu-ui-assets:
    ssh root@{{mister_ip}} 'mkdir -p /media/fat/menu_ui_assets'
    scp docs/assets/menu-ui-demo/*.png root@{{mister_ip}}:/media/fat/menu_ui_assets/

# Run the menu-ui launcher on the device, loading the deployed JS bundle
run-menu-ui: _kill-fpga-users
    ssh -t root@{{mister_ip}} '/media/fat/menu_ui --bundle /media/fat/menu_ui_app.js'

# Run menu-ui with COMPOSITOR_V2 paint path enabled (Phase 4). Host
# paints into a layer source RT; the FPGA's compositor reads it and
# writes the scanout FB. The v2 path is gated on MENU_UI_COMPOSITOR_V2
# while it stabilises; this recipe flips it on without touching the
# default `run-menu-ui` flow.
run-menu-ui-v2: _kill-fpga-users
    ssh -t root@{{mister_ip}} 'MENU_UI_COMPOSITOR_V2=1 /media/fat/menu_ui --bundle /media/fat/menu_ui_app.js'

# Build everything menu-ui needs and deploy + run in one shot
demo-menu-ui: deploy-menu-ui deploy-menu-ui-bundle deploy-menu-ui-assets run-menu-ui

# Same as `demo-menu-ui` but boots the compositor-v2 paint path
# (MENU_UI_COMPOSITOR_V2=1). Use this to validate the Phase 4 host
# migration end-to-end.
demo-menu-ui-v2: deploy-menu-ui deploy-menu-ui-bundle deploy-menu-ui-assets run-menu-ui-v2

# Run the probe on the device (assumes the menu-core .rbf is loaded and the binary is deployed)
probe-menu-core: _kill-fpga-users
    ssh root@{{mister_ip}} '/media/fat/one_fpga_menu_core probe'

# Run the M2b ring round-trip test on the device
ring-test-menu-core: _kill-fpga-users
    ssh root@{{mister_ip}} '/media/fat/one_fpga_menu_core ring-test'

# Run the M2c1 FILL_RECT visual test on the device (look at HDMI)
draw-test-menu-core: _kill-fpga-users
    ssh root@{{mister_ip}} '/media/fat/one_fpga_menu_core draw-test'

# Run the M2c3.1 COPY_RECT visual test on the device (look at HDMI)
texture-test-menu-core: _kill-fpga-users
    ssh root@{{mister_ip}} '/media/fat/one_fpga_menu_core texture-test'

# Run the M2c3.2 A8 + tint visual test on the device (look at HDMI)
a8-test-menu-core: _kill-fpga-users
    ssh root@{{mister_ip}} '/media/fat/one_fpga_menu_core a8-test'

# Run the M2c3.3 SrcAlpha blend visual test on the device (look at HDMI)
blend-test-menu-core: _kill-fpga-users
    ssh root@{{mister_ip}} '/media/fat/one_fpga_menu_core blend-test'

# Run the TTF text-rendering visual test on the device (look at HDMI)
text-test-menu-core: _kill-fpga-users
    ssh root@{{mister_ip}} '/media/fat/one_fpga_menu_core text-test'

# Run the TTF text animation perf test on the device (look at HDMI; reports FPS)
text-anim-menu-core: _kill-fpga-users
    ssh root@{{mister_ip}} '/media/fat/one_fpga_menu_core text-anim'

# Run the M2c2 SET_CLIP / CLEAR_CLIP visual test on the device (look at HDMI)
clip-test-menu-core: _kill-fpga-users
    ssh root@{{mister_ip}} '/media/fat/one_fpga_menu_core clip-test'

# Run the N4.5 SET_RENDER_TARGET visual test on the device (look at HDMI)
rtt-test-menu-core: _kill-fpga-users
    ssh root@{{mister_ip}} '/media/fat/one_fpga_menu_core rtt-test'

# Dump 32 bytes from each FB slot — useful immediately AFTER
# `compositor-v2-test` (or after menu-ui exits) to see whether
# the compositor actually wrote pixels into DDR3, distinguishing
# "painter produced zeros" from "MISTER_FB pointed at wrong FB".
dump-fbs-menu-core: _kill-fpga-users
    ssh root@{{mister_ip}} '/media/fat/one_fpga_menu_core dump-fbs'

# Compositor-v2 (Phase 1 + 2c) smoke test on the device. Flips
# SCANOUT_FB_SELECT and COMPOSITOR_CONTROL live, then holds a
# 5-layer solid scene through the new BRAM-resident layer table →
# scanout_writer → MISTER_FB path. Prints COMPOSITE_FENCE FPS every
# second. Same visual outcome as `layer-draw-menu-core` if the v2
# path works end-to-end.
compositor-v2-test: _kill-fpga-users
    ssh -t root@{{mister_ip}} '/media/fat/one_fpga_menu_core compositor-v2-test'
