//! `/dev/mem` mapping helpers.
//!
//! Wraps [`cyclone_v::memory::DevMemMemoryMapper`] with the volatile
//! byte-copy required when writing into a `/dev/mem` mmap. The kernel
//! maps `/dev/mem` opened with `O_SYNC` as device-grade memory on
//! ARMv7 — vectorized stores generated by ordinary slice writes trip
//! a `SIGBUS`. Always go through [`volatile_copy_to_devmem`] for
//! payload writes.

use cyclone_v::memory::{DevMemMemoryMapper, MemoryMapper};

/// Owning RAII handle for a `/dev/mem` mmap region.
///
/// Tracks the originating physical address for diagnostics, and
/// re-exposes the mapper's pointer accessors. Dropping the handle
/// unmaps the region.
pub struct DevMemMap {
    inner: DevMemMemoryMapper,
    phys_addr: u32,
}

impl DevMemMap {
    /// Map `size` bytes starting at `phys_addr` for read+write access.
    pub fn create(phys_addr: u32, size: usize) -> Result<Self, DevMemError> {
        let inner = DevMemMemoryMapper::create(phys_addr as usize, size).map_err(|detail| {
            DevMemError {
                phys_addr,
                size,
                detail,
            }
        })?;
        Ok(Self { inner, phys_addr })
    }

    /// Mutable raw pointer to the start of the mapped region.
    #[inline]
    pub fn as_mut_ptr(&mut self) -> *mut u8 {
        self.inner.as_mut_ptr::<u8>()
    }

    /// Read-only raw pointer to the start of the mapped region.
    #[inline]
    pub fn as_ptr(&self) -> *const u8 {
        self.inner.as_ptr::<u8>()
    }

    /// Mapped region size in bytes.
    #[inline]
    pub fn len(&self) -> usize {
        self.inner.len()
    }

    /// Physical address the region was mapped from.
    #[inline]
    pub fn phys_addr(&self) -> u32 {
        self.phys_addr
    }
}

/// Failure to mmap a `/dev/mem` region.
#[derive(Debug)]
pub struct DevMemError {
    pub phys_addr: u32,
    pub size: usize,
    pub detail: &'static str,
}

/// Volatile byte-copy from `src` into a `/dev/mem`-mapped buffer.
///
/// Use this for any write into a `/dev/mem` mapping; do not write
/// through a `&mut [u8]` slice. See module-level docs for why.
///
/// # Safety
///
/// `dst` must point to a writable region of at least `src.len()` bytes
/// originating from a valid `/dev/mem` mmap.
#[inline]
pub fn volatile_copy_to_devmem(dst: *mut u8, src: &[u8]) {
    for (i, b) in src.iter().enumerate() {
        // SAFETY: caller guarantees `dst..dst+src.len()` is writable.
        unsafe { core::ptr::write_volatile(dst.add(i), *b) };
    }
}

/// Volatile copy between two regions of the same `/dev/mem` mapping
/// (or between two mappings — the function makes no assumptions).
///
/// Reads `len` bytes from `src` as volatile u32 words and writes them
/// to `dst` as volatile u32 words. Used for in-DDR housekeeping like
/// mirroring the active layer table into the back table.
///
/// # Safety
///
/// - `src` and `dst` must each be readable / writable for `len` bytes
///   and originate from valid `/dev/mem` mmaps (or anything where
///   volatile word-sized accesses are well-defined).
/// - `src`, `dst`, and `len` must all be 4-byte aligned.
/// - The regions may not overlap (callers are not expected to need
///   this; assert in debug to catch misuse).
#[inline]
pub unsafe fn volatile_copy_within_devmem(src: *const u8, dst: *mut u8, len: usize) {
    debug_assert_eq!(src.align_offset(4), 0, "src must be 4-byte aligned");
    debug_assert_eq!(dst.align_offset(4), 0, "dst must be 4-byte aligned");
    debug_assert_eq!(len % 4, 0, "len must be a multiple of 4");
    let words = len / 4;
    let src_w = src as *const u32;
    let dst_w = dst as *mut u32;
    for i in 0..words {
        // SAFETY: caller guarantees the regions are valid for `len`
        // bytes and aligned to 4 bytes.
        let v = unsafe { core::ptr::read_volatile(src_w.add(i)) };
        unsafe { core::ptr::write_volatile(dst_w.add(i), v) };
    }
}
